// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6rEEgS7Vc1BIUjqC9zlyELc1yX6K164k',
    appId: '1:488209695271:web:217d399331834221134402',
    messagingSenderId: '488209695271',
    projectId: 'zayntech-64ee4',
    authDomain: 'zayntech-64ee4.firebaseapp.com',
    storageBucket: 'zayntech-64ee4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhwhbFCvpVKhhM11yVJnOUoO3THAphKnE',
    appId: '1:488209695271:android:e1026065f0e7dc14134402',
    messagingSenderId: '488209695271',
    projectId: 'zayntech-64ee4',
    storageBucket: 'zayntech-64ee4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURqWoH_D13TsXNz1ezcBwoWDh8WhWBsU',
    appId: '1:488209695271:ios:56fc85736bd2ff4c134402',
    messagingSenderId: '488209695271',
    projectId: 'zayntech-64ee4',
    storageBucket: 'zayntech-64ee4.appspot.com',
    iosBundleId: 'com.example.qerscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBURqWoH_D13TsXNz1ezcBwoWDh8WhWBsU',
    appId: '1:488209695271:ios:151779c444b91c0e134402',
    messagingSenderId: '488209695271',
    projectId: 'zayntech-64ee4',
    storageBucket: 'zayntech-64ee4.appspot.com',
    iosBundleId: 'com.example.qerscan.RunnerTests',
  );
}
